# Generated by Django 5.2.7 on 2025-10-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0002_employer_author_vacancy_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='дата подачи')),
                ('want_salary', models.IntegerField(verbose_name='желаемая зп')),
                ('user', models.CharField(verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
        ),
    ]
