# Generated by Django 5.2.7 on 2025-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата подачи'),
        ),
    ]
